# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/juuusto/cplusplus/micro-machines-2020-1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/juuusto/cplusplus/micro-machines-2020-1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/juuusto/cplusplus/micro-machines-2020-1/CMakeFiles /home/juuusto/cplusplus/micro-machines-2020-1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/juuusto/cplusplus/micro-machines-2020-1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named WIDEO_PELI

# Build rule for target.
WIDEO_PELI: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WIDEO_PELI
.PHONY : WIDEO_PELI

# fast build rule for target.
WIDEO_PELI/fast:
	$(MAKE) -f CMakeFiles/WIDEO_PELI.dir/build.make CMakeFiles/WIDEO_PELI.dir/build
.PHONY : WIDEO_PELI/fast

src/Grid.o: src/Grid.cpp.o

.PHONY : src/Grid.o

# target to build an object file
src/Grid.cpp.o:
	$(MAKE) -f CMakeFiles/WIDEO_PELI.dir/build.make CMakeFiles/WIDEO_PELI.dir/src/Grid.cpp.o
.PHONY : src/Grid.cpp.o

src/Grid.i: src/Grid.cpp.i

.PHONY : src/Grid.i

# target to preprocess a source file
src/Grid.cpp.i:
	$(MAKE) -f CMakeFiles/WIDEO_PELI.dir/build.make CMakeFiles/WIDEO_PELI.dir/src/Grid.cpp.i
.PHONY : src/Grid.cpp.i

src/Grid.s: src/Grid.cpp.s

.PHONY : src/Grid.s

# target to generate assembly for a file
src/Grid.cpp.s:
	$(MAKE) -f CMakeFiles/WIDEO_PELI.dir/build.make CMakeFiles/WIDEO_PELI.dir/src/Grid.cpp.s
.PHONY : src/Grid.cpp.s

src/Map.o: src/Map.cpp.o

.PHONY : src/Map.o

# target to build an object file
src/Map.cpp.o:
	$(MAKE) -f CMakeFiles/WIDEO_PELI.dir/build.make CMakeFiles/WIDEO_PELI.dir/src/Map.cpp.o
.PHONY : src/Map.cpp.o

src/Map.i: src/Map.cpp.i

.PHONY : src/Map.i

# target to preprocess a source file
src/Map.cpp.i:
	$(MAKE) -f CMakeFiles/WIDEO_PELI.dir/build.make CMakeFiles/WIDEO_PELI.dir/src/Map.cpp.i
.PHONY : src/Map.cpp.i

src/Map.s: src/Map.cpp.s

.PHONY : src/Map.s

# target to generate assembly for a file
src/Map.cpp.s:
	$(MAKE) -f CMakeFiles/WIDEO_PELI.dir/build.make CMakeFiles/WIDEO_PELI.dir/src/Map.cpp.s
.PHONY : src/Map.cpp.s

src/boost.o: src/boost.cpp.o

.PHONY : src/boost.o

# target to build an object file
src/boost.cpp.o:
	$(MAKE) -f CMakeFiles/WIDEO_PELI.dir/build.make CMakeFiles/WIDEO_PELI.dir/src/boost.cpp.o
.PHONY : src/boost.cpp.o

src/boost.i: src/boost.cpp.i

.PHONY : src/boost.i

# target to preprocess a source file
src/boost.cpp.i:
	$(MAKE) -f CMakeFiles/WIDEO_PELI.dir/build.make CMakeFiles/WIDEO_PELI.dir/src/boost.cpp.i
.PHONY : src/boost.cpp.i

src/boost.s: src/boost.cpp.s

.PHONY : src/boost.s

# target to generate assembly for a file
src/boost.cpp.s:
	$(MAKE) -f CMakeFiles/WIDEO_PELI.dir/build.make CMakeFiles/WIDEO_PELI.dir/src/boost.cpp.s
.PHONY : src/boost.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/WIDEO_PELI.dir/build.make CMakeFiles/WIDEO_PELI.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/WIDEO_PELI.dir/build.make CMakeFiles/WIDEO_PELI.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/WIDEO_PELI.dir/build.make CMakeFiles/WIDEO_PELI.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/tar.o: src/tar.cpp.o

.PHONY : src/tar.o

# target to build an object file
src/tar.cpp.o:
	$(MAKE) -f CMakeFiles/WIDEO_PELI.dir/build.make CMakeFiles/WIDEO_PELI.dir/src/tar.cpp.o
.PHONY : src/tar.cpp.o

src/tar.i: src/tar.cpp.i

.PHONY : src/tar.i

# target to preprocess a source file
src/tar.cpp.i:
	$(MAKE) -f CMakeFiles/WIDEO_PELI.dir/build.make CMakeFiles/WIDEO_PELI.dir/src/tar.cpp.i
.PHONY : src/tar.cpp.i

src/tar.s: src/tar.cpp.s

.PHONY : src/tar.s

# target to generate assembly for a file
src/tar.cpp.s:
	$(MAKE) -f CMakeFiles/WIDEO_PELI.dir/build.make CMakeFiles/WIDEO_PELI.dir/src/tar.cpp.s
.PHONY : src/tar.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... WIDEO_PELI"
	@echo "... edit_cache"
	@echo "... src/Grid.o"
	@echo "... src/Grid.i"
	@echo "... src/Grid.s"
	@echo "... src/Map.o"
	@echo "... src/Map.i"
	@echo "... src/Map.s"
	@echo "... src/boost.o"
	@echo "... src/boost.i"
	@echo "... src/boost.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/tar.o"
	@echo "... src/tar.i"
	@echo "... src/tar.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

